### ISSUE TITLE
Make bash path more portable

### ISSUE THREAD

**Issue by bwidawsk** [ptpb/pb_cli#7]
For those of us in the BSD world, #!/usr/bin/env bash would be much appreciated

**Comment by anarcat** [comment]
i would argue that `/bin/sh` and the removal of bashism would be a better route. :p

**Comment by buhman** [comment]
Not interested in setting precedent for {bsd,my_random_os_here}-portability changes.

That said if someone wants to open a 1-line pr that does this, I would merge it.

**Comment by anarcat** [comment]
well portability would require more than one-line because it would require s/bash/sh/ at first. :p but i understand...

**Comment by bwidawsk** [comment]
I actually think s/bash/sh should just work for pretty much all reasonable implementations of sh. Obviously not the original sh, but s/bash/sh for FreeBSD is fine (the only thing which needs to change is eval requires the script to be in the user's path).

**Comment by anarcat** [comment]
ha! so it *is* a one-line change! :) done in #9.
